services:
  - type: web
    name: finsight-backend
    env: docker
    dockerContext: backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: ohio
    envVars:
      - key: CORS_ORIGINS
        value: "*"

  - type: web
    name: finsight-frontend
    env: docker
    dockerContext: frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    region: ohio
